name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: cache
      uses: actions/cache@v3
      with:
        path: |
          "~/.cache/bazel"
          "~/.cache/bazel-repo"
        key: scratch-${{ runner.os }}-${{ github.sha }}
        restore-keys: |
          scratch-${{ runner.os }}
    - name: build
      env:
        XDG_CACHE_HOME: ~/.cache/bazel-repo
      run: bazel build //...
    - uses: actions/upload-artifact@v3
      with:
        name: papers 
        path: bazel-bin/*.pdf 

