name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - run: mkdir -p ~/.cache/bazel && mkdir ~/.cache/bazel-repo
    - name: cache
      uses: actions/cache@v3
      with:
        path: |
          "/home/runner/.cache/bazel"
          "/home/runner/.cache/bazel-repo"
        key: scratch-${{ runner.os }}-${{ github.sha }}
        restore-keys: |
          scratch-${{ runner.os }}
    - name: build
      run: bazel build --config=ci //...
    - uses: actions/upload-artifact@v3
      with:
        name: papers 
        path: |
          bazel-out/darwin-fastbuild/bin/*.pdf 

